# Site settings
title: Majk Shkurti - CV
description: My Website 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Majk Shkurti
user_description: GIS Developer, with 4+ years of work experience. My overall expertise is Web mapping and Geodesy. I hold a master degree in Geodetic Engineering from Polytechnic University of Tirana, Albania. My experience during and after my studies, is extended in many areas, such as GIS, web mapping, frontend & backend web development, field surveying on objects of particular relevance, geodetic surveys and CAD applications etc. 
user_title: GIS Developer
email: majkshkurti94@gmail.com
twitter_username: majk_shkurti
github_username:  majkshkurti
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-140419181-1"

exclude: ['package.json', 'src' , 'node_modules']
